#
# Prerequisites:
#   (*) Clone the designated AS360 KNI git repository
#   (*) Ensure you are logged in the designated docker registry (e.g., via using the 'docker login' command),
#       or define 2 environment variables holding the registry credentials: HCLCR_USERNAME and HCLCR_PASSWORD
#   (*) Ensure you are running from a folder that contains the helmfile.d folder
#   (*) Place under helmfile.d/helmFileCustomizations your pre-defined customization file named: singular-singular.clusterKit.yaml
#
# Usage:
#   (*) Install: helmfile sync
#     Ensure one of the following:
#       1. Define an environment variable as follows:
#         Name: AS360_KNI_JSON_CONFIG_AS_BASE64
#         Value: The designated registry docker config file, encoded in Base64
#       2. Verify an already configured docker config file is residing under the home folder of the user (e.g., ~/.docker/config.json)
#   (*) Uninstall: helmfile destroy
#

helmfiles:
  - path: ./helm.d/helmfile-ASCP.yaml
  - path: ./helm.d/helmfile-ASRA.yaml

