#
# Prerequisites:
#   (*) Clone the designated AS360 KNI git repository
#   (*) Ensure you are logged in the designated docker registry (e.g., via using the 'docker login' command),
#       or define 2 environment variables holding the registry credentials: HCLCR_USERNAME and HCLCR_PASSWORD
#   (*) Ensure you are running from a folder that contains the helmfile.d folder
#   (*) Place under helmfile.d/helmFileCustomizations your pre-defined customization file named: singular-singular.clusterKit.yaml
#
# Usage:
#   (*) Install: helmfile sync
#     Ensure one of the following:
#       1. Define an environment variable as follows:
#         Name: AS360_KNI_JSON_CONFIG_AS_BASE64
#         Value: The designated registry docker config file, encoded in Base64
#       2. Verify an already configured docker config file is residing under the home folder of the user (e.g., ~/.docker/config.json)
#   (*) Uninstall: helmfile destroy
#
environments:
  default:
    values:
    - global:
        multiTenantDeploymentDifferentiator: ''
        runtime:
          siteName: singular
          clusterName: singular
    - environment:
        helmRepositoryName: hclcr
        helmRepositoryContext: appscan360/ascp-k8s-helm-packages
        releaseName: appscan360-ascp
        releaseNamespace: hcl-appscan-ascp
        dockerRegistryAddress: hclcr.io
        dockerRegistryProject: appscan360
        dockerRegistryContext: appscan360/ascp-k8s-docker-images
  # *** Non production/customer environments (to be removed in formal publication) - BEGIN ***
  as360-stage:
    values:
    - global:
        multiTenantDeploymentDifferentiator: ''
        runtime:
          siteName: singular
          clusterName: singular
    - environment:
        helmRepositoryName: hclcr
        helmRepositoryContext: appscan360-staging/ascp-k8s-helm-packages
        releaseName: appscan360-ascp
        releaseNamespace: hcl-appscan-ascp
        dockerRegistryAddress: hclcr.io
        dockerRegistryProject: appscan360-staging
        dockerRegistryContext: appscan360-staging/ascp-k8s-docker-images
  as360-dev:
    values:
    - global:
        multiTenantDeploymentDifferentiator: kni-release-asop
        runtime:
          siteName: ldc
          clusterName: expo
    - environment:
        helmRepositoryName: asocacr
        helmRepositoryContext: ascp-k8s-helm-packages
        releaseName: as360-ascp
        releaseNamespace: hcl-appscan-ascp-kni-release-asop
        dockerRegistryAddress: asocregistryea.azurecr.io
        dockerRegistryProject: ''
        dockerRegistryContext: ascp-k8s-docker-images
  # *** Non production/customer environments (to be removed in formal publication)- END ***
---
helmDefaults:
  cleanupOnFail: true
  wait: true
  waitForJobs: true
  atomic: true
  timeout: 600
  createNamespace: true
  deleteWait: true

repositories:
- name: stakater
  url: https://stakater.github.io/stakater-charts
  oci: false
- name: hclcr
  url: hclcr.io
  oci: true
# *** Non production/customer repositories (to be removed in formal publication) - BEGIN ***
- name: asocacr
  url: asocregistryea.azurecr.io
  oci: true
# *** Non production/customer repositories (to be removed in formal publication) - END ***

releases:
- name: reloader
  namespace: '{{ .Values.environment.releaseNamespace }}'
  chart: stakater/reloader
  values:
  - reloader:
      watchGlobally: false
      deployment:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    # WA for a defect in the latest chart!
    nameOverride: reloader
    fullnameOverride: reloade
- name: '{{ .Values.environment.releaseName }}'
  namespace: '{{ .Values.environment.releaseNamespace }}'
  chart: '{{ .Values.environment.helmRepositoryName }}/{{ .Values.environment.helmRepositoryContext }}/ascp-dart-prime'
  version: 1.6.0-rc.32-release-asop
  needs:
  - reloader
  values:
#  - helmFileCustomizations/siteKit.yaml
#  - helmFileCustomizations/{{ .Values.global.runtime.siteName }}.siteKit.yaml
  - helmFileCustomizations/clusterKit.yaml
  - helmFileCustomizations/{{ .Values.global.runtime.siteName }}-{{ .Values.global.runtime.clusterName }}.clusterKit.yaml
  - global:
      multiTenantDeploymentDifferentiator: {{ .Values.global.multiTenantDeploymentDifferentiator }}
      isOnPremisesDeploymentViaKNI: true
      runtime:
        customerName: ASOP
        siteName: {{ .Values.global.runtime.siteName }}
        clusterName: {{ .Values.global.runtime.clusterName }}
      workload:
        affiliatedSidecarsProject: {{ .Values.environment.dockerRegistryProject }}
        container:
          image:
            registry: {{ .Values.environment.dockerRegistryAddress }}
            repository: {{ .Values.environment.dockerRegistryContext }}
            pullPolicy: IfNotPresent
            pullSecrets:
            - ascp-docker-registry-secret
        engageEgressFencing: true
        dockerPrivateRegistry:
          secret:
            enabled: true
            data:
{{- if env "AS360_KNI_JSON_CONFIG_AS_BASE64" }}
              jsonConfigAsBase64: {{ env "AS360_KNI_JSON_CONFIG_AS_BASE64" }}
{{- else }}
              jsonConfigAsBase64: {{ readFile (printf "%s/%s" (env "HOME") ".docker/config.json") | b64enc }}
{{- end }}
      storage:
        pvc:
          linux:
            enabled: true
            accessMode: ReadWriteMany