#
# Prerequisites:
#   (*) Clone the designated AS360 KNI git repository
#   (*) Ensure you are logged in the designated docker registry (e.g., via using the 'docker login' command),
#       or define 2 environment variables holding the registry credentials: HCLCR_USERNAME and HCLCR_PASSWORD
#
# Usage:
#   (*) Install: helmfile sync
#     Ensure one of the following:
#       1. Define an environment variable as follows:
#         Name: AS360_KNI_JSON_CONFIG_AS_BASE64
#         Value: The designated registry docker config file, encoded in Base64
#       2. Verify an already configured docker config file is residing under the home folder of the user (e.g., ~/.docker/config.json)
#   (*) Uninstall: helmfile destroy
# 


environments:
 default:
  values:
  - asraHelmRegistry: {{ env "ASRA_HELM_REG" | default "hclcr.io" }}
    asraHelmRepo: hcl_asra/{{ env "ASRA_HELM_REPO" | default "appscan360/asra-k8s-helm-packages" }}/asra
    asraImageRegistry: {{ env "ASRA_IMAGE_REG" | default "hclcr.io" }}
    asraImageRepo: {{ env "ASRA_IMAGE_REPO" | default "appscan360/asra-k8s-docker-images" }}/asra

---

repositories:
- name: hcl_asra
  url: hclcr.io
  oci: true

helmDefaults:
 atomic: true
 cleanupOnFail: false
 createNamespace: true
 deleteWait: true
 timeout: 600
 wait: true
 waitForJobs: true

releases:
- name: asra
  namespace: hcl-appscan-asra
  chart: {{ .Values.asraHelmRepo }}
  version: 2.7.0-164GA
  values:
  - image:
     registry: {{ .Values.asraImageRegistry }}
     repository: {{ .Values.asraImageRepo }}
     asraImagePullSecret:
{{- if env "AS360_KNI_JSON_CONFIG_AS_BASE64" }}
              {{ env "AS360_KNI_JSON_CONFIG_AS_BASE64" }}
{{- else }}
              {{ ((readFile (printf "%s/%s" (env "HOME") ".docker/config.json")) | b64enc) }}
{{- end }}
