global:
  mainProductReleaseVersionNumber: 1.6.0-rc.32
  mainProductReleaseVersionMarkup: 1.6.0-rc.32-release-asop
  isOnPremisesDeployment: true
  customer:
    certificate:
      ingress:
        enabled: ~
        secret:
          name: appscan-customer-ingress-certificate-secret
          data:
            caCrtAsBase64: ~
            tlsCrtAsBase64: ~
            tlsKeyAsBase64: ~
  workload:
    engageEgressFencing: ~
    replicasCountOverride: ~
    container:
      image:
        registry: ~
        repository: ~
        pullPolicy: ~
        pullSecrets:
        - ~
    dockerPrivateRegistry:
      secret:
        enabled: false
    sidecars:
    - name: pod-initializer
      imageUp2date: false
      imageName: ascp-dart-pod-initializer
      imageTag: 1.3.0
    - name: dbmigrator-runner
      imageDirectUpdate: true
      imageName: ascp-mr-db-migrator-runner
      imageTag: 2025-05-12-1006-21-release-asop
  storage:
    pvc:
      linux:
        enabled: true
        accessMode: ~
        storageClassName: ~
        volumeName: ~
        requestedCapacity: ~
      windows:
        enabled: false
  ca:
    seed:
      enabled: false
    root:
      secret:
        data:
          tlsCrtAsBase64: ~
          tlsKeyAsBase64: ~
  ingress:
    controller:
      capabilities:
        isHttpsBackendProtocolSupported: ~
    internal:
      class: ~
      host:
        domain: ~
        subDomain: ~
  network:
    domainSuffix: ~
  configuration:
    disclosed:
      siteUrl: ~
      ldapDomain: ~
      ldapUsername: ~
      ldapAuthorizedGroups: ~
      ldapSsl: ~
      ldapTargetOU: ~
      mailSmtpHost: ~
      mailSmtpPort: ~
      mailSmtpUserName: ~
      mailSmtpEnableSsl: ~
      externalIDPMode: ~
      upstreamProxyHost: ~
      upstreamProxyPort: ~
      upstreamProxyUsername: ~
    confidential:
      defaultConnection: ~
      ldapPassword: ~
      upstreamProxyPassword: ~
      agentsApiKey: ~
      userApiDPKey: ~
      mailSmtpPassword: ~
      resourceSignerKey: ~
ascp-user-portal-ui:
  enabled: true
  common:
    ingress:
      external:
        enabled: false
ascp-domain-challenger:
  enabled: true
  common:
    workload:
      mainContainer:
        env:
          additionalEnvs:
          - name: Settings__Environment
            value: ASoP
ascp-egress-gatekeeper:
  enabled: true
  common:
    workload:
      mainContainer:
        env:
          additionalEnvs:
          - name: ProxySettings__UpstreamProxy__Host
            value: '{{ .Values.global.configuration.disclosed.upstreamProxyHost }}'
          - name: ProxySettings__UpstreamProxy__Port
            value: '{{ .Values.global.configuration.disclosed.upstreamProxyPort }}'
          - name: ProxySettings__UpstreamProxy__Username
            value: '{{ .Values.global.configuration.disclosed.upstreamProxyUsername }}'
          - name: ProxySettings__UpstreamProxy__Password
            value: '{{ .Values.global.configuration.confidential.upstreamProxyPassword }}'
ascp-mr-tasks-manager:
  enabled: true
  common:
    workload:
      sharedFileStorageMountPathSuffix: ''
      sidecars:
      - name: report-job
        imageDirectUpdate: true
        imageName: ascp-mr-report-processor
        imageTag: 2025-05-12-1006-21-release-asop
      - name: resultsprocessor-job
        imageDirectUpdate: true
        imageName: ascp-mr-tasks-manager
        imageTag: 2025-05-12-1006-21-release-asop
      - name: pss-presence-provisioner
        imageDirectUpdate: true
        imageName: ascp-pss-presence-provisioner
        imageTag: 2024-10-28-1340-57-release-asop
      - name: pss-tunnel-provisioner
        imageDirectUpdate: true
        imageName: ascp-pss-tunnel-provisioner
        imageTag: 2024-10-30-1014-12-release-asop
      - name: sast-job
        imageMarkerTag: as360
        imageVersionLabelName: version
        imageRepository: sast-k8s-docker-images
        imageIsAffiliated: true
        imageName: sastagent
        imageTag: 8.0.1631
      - name: sast-tools-provisioner
        imageMarkerTag: as360
        imageVersionLabelName: version
        imageRepository: sast-k8s-docker-images
        imageIsAffiliated: true
        imageName: sastclient-tools
        imageTag: 1.0.0_P83-CU.8.0.1631-GO.2.2.0
      - name: dast-job
        imageMarkerTag: as360
        imageVersionLabelName: version
        imageRepository: dast-k8s-docker-images
        imageIsAffiliated: true
        imageName: appscan-linux-dast-runner
        imageTag: as360-1.6.0.606
      initContainers:
      - name: ascp-pss-presence-provisioner
        image: '{{ include "ascp-dart-common-helm-chart.sideCarImageURL" (dict "TopLevelScope" $ "SideCarsList" .Values.common.workload.sidecars "SideCarName" "pss-presence-provisioner") }}'
        imagePullPolicy: '{{ .Values.global.workload.container.image.pullPolicy }}'
        env:
        - name: ASCP_PSS_PRESENCE_TOOL_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/ascp-pss-presence'
        volumeMounts:
        - name: shared-file-storage-volume
          mountPath: '{{ .Values.common.workload.sharedFileStorageMountPath }}'
      - name: ascp-pss-tunnel-provisioner
        image: '{{ include "ascp-dart-common-helm-chart.sideCarImageURL" (dict "TopLevelScope" $ "SideCarsList" .Values.common.workload.sidecars "SideCarName" "pss-tunnel-provisioner") }}'
        imagePullPolicy: '{{ .Values.global.workload.container.image.pullPolicy }}'
        env:
        - name: ASCP_PSS_TUNNEL_TOOL_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/ascp-pss-tunnel'
        volumeMounts:
        - name: shared-file-storage-volume
          mountPath: '{{ .Values.common.workload.sharedFileStorageMountPath }}'
      - name: sast-tools-provisioner
        image: '{{ include "ascp-dart-common-helm-chart.sideCarImageURL" (dict "TopLevelScope" $ "SideCarsList" .Values.common.workload.sidecars "SideCarName" "sast-tools-provisioner") }}'
        imagePullPolicy: '{{ .Values.global.workload.container.image.pullPolicy }}'
        env:
        - name: SAST_TOOL_WIN_CLI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/wincli'
        - name: SAST_TOOL_WIN_GUI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/wingui'
        - name: SAST_TOOL_LINUX_CLI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/linuxcli'
        - name: SAST_TOOL_LINUX_GUI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/linuxgui'
        - name: SAST_TOOL_MAC_CLI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/maccli'
        - name: SAST_TOOL_MAC_GUI_PATH
          value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/macgui'
        - name: SAST_TOOL_SERVICE_TARGET_URL
          value: '{{ .Values.global.configuration.disclosed.siteUrl }}'
        volumeMounts:
        - name: shared-file-storage-volume
          mountPath: '{{ .Values.common.workload.sharedFileStorageMountPath }}'
      mainContainer:
        env:
          additionalEnvs:
          - name: Settings__MseServerName
            value: ~
          - name: ASCP_PSS_PRESENCE_TOOL_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/ascp-pss-presence'
          - name: ASCP_PSS_TUNNEL_TOOL_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/ascp-pss-tunnel'
          - name: SAST_TOOL_WIN_CLI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/wincli'
          - name: SAST_TOOL_WIN_GUI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/wingui'
          - name: SAST_TOOL_LINUX_CLI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/linuxcli'
          - name: SAST_TOOL_LINUX_GUI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/linuxgui'
          - name: SAST_TOOL_MAC_CLI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/maccli'
          - name: SAST_TOOL_MAC_GUI_PATH
            value: '{{ .Values.common.workload.sharedFileStorageMountPath }}{{ .Values.common.workload.sharedFileStorageMountPathSuffix }}/Tools/sasttool/macgui'
          - name: SAST_TOOL_SERVICE_TARGET_URL
            value: '{{ .Values.global.configuration.disclosed.siteUrl }}'
ascp-mr-user-api:
  enabled: true
  common:
    workload:
      sharedFileStorageMountPathSuffix: ''
      mainContainer:
        env:
          additionalEnvs:
          - name: Settings__MseServerName
            value: ~
    certificate:
      ingress:
        internal:
          enabled: true
        external:
          enabled: false
        federation:
          enabled: false
    ingress:
      internal:
        enabled: true
        rules:
        - hostOverride: null
          appSubDomain: null
          paths:
          - appServiceName: null
            appServicePortName: null
            appPath: /api
            appPathType: ImplementationSpecific
          - appServiceName: null
            appServicePortName: null
            appPath: /swagger
            appPathType: ImplementationSpecific
      external:
        enabled: false
      federation:
        enabled: false
ascp-mr-scanners-api:
  enabled: true
  common:
    workload:
      sharedFileStorageMountPathSuffix: ''
    certificate:
      ingress:
        internal:
          enabled: false
    ingress:
      internal:
        enabled: false
ascp-mr-presence-api:
  enabled: true
  common:
    workload:
      sharedFileStorageMountPathSuffix: ''
    certificate:
      ingress:
        internal:
          enabled: true
        external:
          enabled: false
    ingress:
      internal:
        enabled: true
        rules:
        - hostOverride: null
          appSubDomain: null
          paths:
          - appServiceName: null
            appServicePortName: null
            appPath: /presence
            appPathType: ImplementationSpecific
      external:
        enabled: false